Repository lucas-mrq/LibrarIST, pull requests merged in 2023-06, with the labels that each got.

#7 Feature 3- Add photo to library info panel
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
  app/src/main/res/drawable/fake_map.PNG
  app/src/main/res/drawable/free_library_example.jpg
  app/src/main/res/layout/activity_library_info.xml
Labels: improvement

#9 Feature 2 code bar scan
  .idea/kotlinc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/CheckIn.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/NewBook.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/newBook.java
  app/src/main/res/drawable/exemple.jpg
  app/src/main/res/layout/activity_check_in.xml
  app/src/main/res/layout/activity_new_book.xml
Labels: feature

#12 solve bug
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
Labels: bug

#18 Feature-7 Add a camera photo for new books
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/NewBook.java
  app/src/main/res/layout/activity_new_book.xml
Labels: feature

#20 Feature 8 add a dark theme
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/BookInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/CheckIn.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/MainActivity.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/NewBook.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/SearchActivity.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/ThemeManager.java
  app/src/main/res/layout/activity_book_info.xml
  app/src/main/res/layout/activity_check_in.xml
  app/src/main/res/layout/activity_library_info.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_book.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/bottom_layout.xml
  app/src/main/res/raw/darkmap.json
  app/src/main/res/raw/lightmap.json
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature

#34 Feature 12 Show map on Library Info
  app/build.gradle
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/BookInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/CheckIn.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/MainActivity.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/NewBook.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/SearchActivity.java
  app/src/main/res/layout/activity_library_info.xml
Labels: feature

#37 Feature 10 Save Favorite Library on Memory
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/BookInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/MainActivity.java
Labels: feature

#41 Bonus Feature 5 Localization [5%]
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/BookInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/CheckIn.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/LibraryInfo.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/MainActivity.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/NewBook.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/SearchActivity.java
  app/src/main/java/pt/ulisboa/tecnico/cmov/freelibrary/models/Book.java
  app/src/main/res/layout/activity_book_info.xml
  app/src/main/res/layout/activity_check_in.xml
  app/src/main/res/layout/activity_library_info.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_book.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values/strings.xml
Labels: bonus feature
